### ISSUE TITLE
Events bubbling

### ISSUE THREAD

**Issue by bsboris** [ai/evil-blocks#37]
Hi, Andrei,

Thank you for this awesome tool!

I have a problem with event bubbling. If block have global event on it (like `"on click": ->`), the event only fires when click occurs on the literal block element (`div@@block`) and doesn't fire when I click any inner elements (`div@@block > span`). It looks like #27 addressed this issue, but I couldn't find merge commit. Is there any workaround for this issue?

**Comment by ai** [comment]
Global events are only for cross-block communications
